apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-django
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: web-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-deploy
    spec:
      containers:
        - name: nginx-d
          image: simsh1031/mynginxd:0.3
          ports:
            - containerPort: 80

        - name: django-web
          image: simsh1031/mydjango:0.2
          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
